# Generated by Django 4.1.1 on 2023-06-23 18:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('data', models.FileField(storage=django.core.files.storage.FileSystemStorage, upload_to='D:\\Projects\\Django\\portfolio\\static/media/')),
                ('data_type', models.CharField(blank=True, choices=[('model', 'Model'), ('weights', 'Weights')], default='model', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.FileField(storage=django.core.files.storage.FileSystemStorage, upload_to='D:\\Projects\\Django\\portfolio\\static/media/')),
                ('description', models.TextField(max_length=4000)),
                ('link', models.TextField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('skills', models.ManyToManyField(related_name='skills', to='projects.skill')),
            ],
        ),
    ]
