# Generated by Django 4.1.1 on 2023-06-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
