# Generated by Django 4.1.1 on 2023-06-25 09:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='data_transformer',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage, upload_to='D:\\Projects\\Django\\portfolio\\static/media/pipelines'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='data',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage, upload_to='D:\\Projects\\Django\\portfolio\\static/media/models'),
        ),
    ]
